import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {parsePacket} from '../src/packet.mjs';
const server=createServer((req,res)=>{res.setHeader('Content-Type','text/html');if(req.url==='/performance')return res.end('<form>'+Array.from({length:100},(_,i)=>`<input id="f${i}" name="field${i}">`).join('')+'</form>');if(req.url.startsWith('/captcha'))return res.end('<div class="g-recaptcha"><input id="robot" type="checkbox"></div><script>window.interactions=0;for(const name of ["click","input","change"])document.addEventListener(name,()=>window.interactions++);</script>');if(req.url==='/frame')return res.end('<label>Frame answer<input id="frame_answer" name="frame_answer"></label>');const family=req.url.slice(1),port=server.address().port;res.end(`<!doctype html><h1>${family} fixture</h1><form id="apply"><label>First Name<input id="first_name" name="first_name"></label><label>Last Name<input id="last_name" name="last_name"></label><label>Email<input id="email" name="email" type="email"></label><label>Phone<input id="phone" name="phone" type="tel"></label><textarea id="answer" name="answer"></textarea><input id="consent" name="consent" type="checkbox"><input name="resume" type="file" style="display:none"><input type="password" name="password" value="excluded-password"><input type="hidden" name="csrf_token" value="excluded-token"><iframe id="challenge" src="/captcha?recaptcha"></iframe>${family==='greenhouse'?`<iframe id="greenhouse_iframe" name="greenhouse_iframe" src="http://job-boards.greenhouse.io:${port}/frame"></iframe>`:''}<button type="submit">Submit</button></form><script>window.submits=0;document.getElementById('apply').addEventListener('submit',e=>{e.preventDefault();window.submits++});</script>`)});
await new Promise(r=>server.listen(0,'0.0.0.0',r));const port=server.address().port,base=`http://127.0.0.1:${port}`;const dir=await mkdtemp(path.join(os.tmpdir(),'handoff-browser-'));const ext=path.join(dir,'extension');await cp('dist/extension',ext,{recursive:true});const manifest=JSON.parse(await readFile(path.join(ext,'manifest.json')));assert.equal(manifest.host_permissions,undefined);assert.ok(!manifest.permissions.includes('cookies'));assert.ok(!manifest.content_scripts);manifest.host_permissions=[base+'/*',`http://job-boards.greenhouse.io:${port}/*`];await writeFile(path.join(ext,'manifest.json'),JSON.stringify(manifest));
let context;const errors=[],coverage=[];try{
 context=await chromium.launchPersistentContext(path.join(dir,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`,'--host-resolver-rules=MAP job-boards.greenhouse.io 127.0.0.1','--no-proxy-server']});
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const id=new URL(worker.url()).host;const popup=await context.newPage();popup.on('pageerror',e=>errors.push(e.message));await popup.goto(`chrome-extension://${id}/popup.html`);
 const cmd=(type,extra={})=>popup.evaluate(async m=>{const r=await chrome.runtime.sendMessage(m);if(!r.ok)throw Error(r.error);return r.data},{type,...extra});
 const example=JSON.parse(await readFile('handoffs/examples/greenhouse-example.json'));
 for(const family of ['greenhouse','lever','ashby','smartrecruiters']){
  const app=await context.newPage();await app.goto(base+'/'+family);await app.waitForLoadState('load');const tabId=await popup.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,app.url());
  const fields=[{name:'first_name',selectors:['#first_name'],value:'Alex',type:'text'},{name:'last_name',selectors:['#last_name'],value:'Example',type:'text'},{name:'email',selectors:['#email'],value:'alex@example.com',type:'email'},{name:'phone',selectors:['#phone'],value:'555-0100',type:'tel'},{selectors:['#answer'],value:'Exact answer\nSecond line',type:'textarea'},{selectors:['#consent'],value:true,type:'checkbox'}];
  if(family==='greenhouse')fields.push({name:'frame_answer',selectors:['#frame_answer'],value:'Frame filled',type:'text',frame_url:`http://job-boards.greenhouse.io:${port}/frame`});
  const packet={...example,id:crypto.randomUUID(),application_url:app.url(),fields};await popup.locator('#json').fill(JSON.stringify(packet));await popup.locator('#import').click();await popup.getByText('Packet imported. Nothing was filled automatically.').waitFor();assert.equal(await app.locator('#first_name').inputValue(),'');
  const started=performance.now(),result=await cmd('restore',{tabId}),elapsed=performance.now()-started;assert.equal(result.filled,fields.length,JSON.stringify(result));assert.ok(elapsed<3000,`${family}: ${elapsed}ms`);assert.equal(await app.locator('#email').inputValue(),'alex@example.com');assert.equal(await app.locator('#phone').inputValue(),'555-0100');if(family==='greenhouse')assert.equal(await app.frameLocator('#greenhouse_iframe').locator('#frame_answer').inputValue(),'Frame filled');assert.ok(result.warnings.some(s=>s.includes('manually')));
  assert.equal((await cmd('restore',{tabId})).filled,0);assert.equal(await app.locator('#consent').isChecked(),true);assert.equal(await app.evaluate(()=>window.submits),0);assert.equal(await app.frameLocator('#challenge').locator('body').evaluate(()=>window.interactions),0);
  const exported=await cmd('capture',{tabId});parsePacket(exported.packet);assert.ok(exported.packet.fields.some(f=>f.value==='alex@example.com'));assert.ok(!JSON.stringify(exported.packet).includes('excluded-password'));assert.ok(!JSON.stringify(exported.packet).includes('excluded-token'));assert.equal(exported.capture.captcha_detected,true);if(family==='greenhouse')assert.ok(exported.packet.fields.some(f=>f.value==='Frame filled'));
  coverage.push({family,filled:result.filled,expected:fields.length,elapsed_ms:Math.round(elapsed),captcha_interactions:0,submits:0});await app.close();
 }
 const perf=await context.newPage();await perf.goto(base+'/performance');const perfId=await popup.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,perf.url());await cmd('import',{packet:{...example,id:crypto.randomUUID(),application_url:perf.url(),fields:Array.from({length:100},(_,i)=>({selectors:[`#f${i}`],value:'Test '+i,type:'text'}))}});const perfStart=performance.now();const perfResult=await cmd('restore',{tabId:perfId});const perfMs=performance.now()-perfStart;assert.equal(perfResult.filled,100);assert.ok(perfMs<3000);coverage.push({family:'100-standard-fields',filled:100,expected:100,elapsed_ms:Math.round(perfMs)});await perf.close();
 const app=await context.newPage();await app.goto(base+'/lever');const tabId=await popup.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,app.url());await cmd('import',{packet:{...example,id:crypto.randomUUID(),application_url:app.url(),fields:[],profile_overlay:{first:'Alex',last:'Example',email:'alex@example.com',phone:'555-0100'}}});assert.equal((await cmd('restore',{tabId})).filled,4);
 await popup.locator('#json').fill(JSON.stringify({...example,schema_version:'2.0'}));await popup.locator('#import').click();await popup.getByText(/Unsupported packet schema/).waitFor();
 for(let i=0;i<6;i++)await cmd('import',{packet:{...example,id:crypto.randomUUID(),application_url:app.url()}});assert.equal((await cmd('state')).packets.length,5);await assert.rejects(cmd('submitted',{confirm:false}),/Confirm/);assert.equal((await cmd('submitted',{confirm:true})).status,'submitted');assert.equal(await app.evaluate(()=>window.submits),0);
 const capture=await app.evaluate(await readFile('dist/capture-form-state.js','utf8'));assert.ok(capture.fields.length>=4);let chunked;for(const file of (await readdir('dist/capture-chunks')).filter(x=>x.endsWith('.js')).sort()){const code=await readFile('dist/capture-chunks/'+file,'utf8');assert.ok(code.length<=2000);chunked=await app.evaluate(code)}assert.deepEqual(chunked.fields,capture.fields);
 await mkdir('.test-output',{recursive:true});await popup.reload();await popup.locator('#summary').waitFor();await popup.screenshot({path:'.test-output/handoff-popup.png',fullPage:true});assert.deepEqual(errors,[]);await writeFile('.test-output/browser-report.json',JSON.stringify({passed:true,coverage,profile_fallback:true,capture_chunks:true,packet_history_limit:5,production_writes:0,real_employer_submissions:0,limitations:['Controlled ATS-like fixtures, not live employer layout certification.','Fixture-origin permissions are pre-granted only in the temporary test manifest.']},null,2));console.log(JSON.stringify({passed:true,coverage,errors},null,2));
}finally{await context?.close();await new Promise(r=>server.close(r))}
