import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {validateBundle,validateDiagnostics,installBundle,setupAgent,sha256,syncDocs,compatible} from '../cli/jobs-workflow.mjs';
const makeBundle=(version='0.3.0')=>{const info={version,build_hash:'a'.repeat(64),storage_schema:1};return {format:1,...info,files:{'manifest.json':Buffer.from(JSON.stringify({name:'JobsUtilityExtension',manifest_version:3,version})).toString('base64'),'build-info.json':Buffer.from(JSON.stringify(info)).toString('base64'),'worker.js':Buffer.from('/* bundled trusted code */').toString('base64')}}};
test('safe packages, atomic updates, rollback copies, interrupted staging and identity preservation',async()=>{const home=await fs.mkdtemp(path.join(os.tmpdir(),'jobs-updater-'));try{
 const target=path.join(home,'installed'),state=path.join(home,'browser-storage.json');await fs.writeFile(state,'drafts and credentials remain outside installed code');
 const raw=Buffer.from(JSON.stringify(makeBundle()));const artifact={size:raw.length,sha256:sha256(raw)};const bundle=validateBundle(raw,artifact);assert.throws(()=>validateBundle(raw,{...artifact,sha256:'b'.repeat(64)}),/checksum/);
 const unsafe=makeBundle();unsafe.files['../escape']='eA==';const bytes=Buffer.from(JSON.stringify(unsafe));assert.throws(()=>validateBundle(bytes,{size:bytes.length,sha256:sha256(bytes)}),/Unsafe/);
 await installBundle(target,bundle);const manifest=JSON.parse(await fs.readFile(path.join(target,'manifest.json')));manifest.key='existing-public-key';await fs.writeFile(path.join(target,'manifest.json'),JSON.stringify(manifest));
 await assert.rejects(installBundle(target,bundle,{interruptAfterStage:true}),/interrupted/);assert.equal(JSON.parse(await fs.readFile(path.join(target,'manifest.json'))).key,'existing-public-key');
 const changed=makeBundle('0.3.1');const r=Buffer.from(JSON.stringify(changed));const second=validateBundle(r,{size:r.length,sha256:sha256(r)});const update=await installBundle(target,second);assert.equal(update.status,'reload_required');assert.equal(JSON.parse(await fs.readFile(path.join(target,'manifest.json'))).key,'existing-public-key');assert.equal(JSON.parse(await fs.readFile(path.join(update.backup,'manifest.json'))).version,'0.3.0');assert.equal(await fs.readFile(state,'utf8'),'drafts and credentials remain outside installed code');
 await fs.mkdir(path.join(home,'unrelated'));await assert.rejects(installBundle(path.join(home,'unrelated'),bundle),/unrelated/);
}finally{await fs.rm(home,{recursive:true,force:true})}});
test('fresh runtime reports, wrong IDs, busy queues, and post-reload version checks',()=>{const report={schema_version:1,generated_at:new Date().toISOString(),extension_id:'a'.repeat(32),version:'0.3.0',build_hash:'a'.repeat(64),active_captures:0,pending_queue:0,active_attempts:0,collection_sites:0,safe_to_reload:true};assert.equal(validateDiagnostics(report,{idle:true}).version,'0.3.0');assert.throws(()=>validateDiagnostics({...report,pending_queue:1},{idle:true}),/busy/);assert.throws(()=>validateDiagnostics(report,{version:'0.3.1'}),/intended/);assert.throws(()=>validateDiagnostics(report,{expectedId:'b'.repeat(32)}),/different/);assert.throws(()=>validateDiagnostics({...report,generated_at:'2000-01-01T00:00:00Z'}),/Fresh/)});
test('bootstrap preserves instructions, is idempotent, and installs no credentials',async()=>{const home=await fs.mkdtemp(path.join(os.tmpdir(),'jobs-agent-'));try{await fs.mkdir(path.join(home,'.codex'));await fs.writeFile(path.join(home,'.codex/AGENTS.md'),'Keep my existing rules.\n');for(const target of ['codex','claude','hermes']){await setupAgent(target,home);const again=await setupAgent(target,home);assert.equal(again.changed,false);assert.match(await fs.readFile(again.skill,'utf8'),/canonical guide/);assert.ok((await fs.readFile(again.skill,'utf8')).startsWith('---\nname:'))}assert.match(await fs.readFile(path.join(home,'.codex/AGENTS.md'),'utf8'),/^Keep my existing rules/)}finally{await fs.rm(home,{recursive:true,force:true})}});
test('sync detects revisions; offline cached docs never mean compatible',async()=>{const home=await fs.mkdtemp(path.join(os.tmpdir(),'jobs-sync-'));try{const base='https://www.kevinc.dev',d={revision:'first',contract_hash:'a'.repeat(64),api_version:'1.1.0',supported_clients:{cli:{min:'0.3.0',max_major:0}},links:Object.fromEntries(['guide','openapi','changes','releases'].map(n=>[n,base+'/'+n]))};const fetcher=async url=>new Response(String(url).endsWith('discovery')?JSON.stringify(d):String(url).endsWith('guide')?'Canonical guide':JSON.stringify({releases:[]}));assert.equal((await syncDocs(home,base,fetcher)).changed,true);assert.equal((await syncDocs(home,base,fetcher)).changed,false);d.revision='second';assert.equal((await syncDocs(home,base,fetcher)).changed,true);const offline=await syncDocs(home,base,async()=>{throw Error('offline')});assert.equal(offline.compatible,false);assert.ok(offline.cached_guide);assert.equal(compatible({...d,supported_clients:{cli:{min:'1.0.0',max_major:1}}}),false)}finally{await fs.rm(home,{recursive:true,force:true})}});
