import {parsePacket} from './packet.mjs';
const $=id=>document.getElementById(id);let selected=null,lastReport=null;
const message=async(type,extra={})=>{const r=await chrome.runtime.sendMessage({type,...extra});if(!r?.ok)throw Error(r?.error||'Extension did not respond');return r.data};
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':''}
async function refresh(){const s=await message('state');selected=s.packets.find(w=>w.packet.id===s.selected)||null;$('history').replaceChildren(...s.packets.map(w=>new Option(`${w.packet.company||w.packet.id} · ${w.local_status}`,w.packet.id)));$('history').value=s.selected||'';$('summary').textContent=selected?`${selected.packet.company||'Company not recorded'} — ${selected.packet.role||'Role not recorded'}\n${selected.packet.application_url}\n${selected.packet.blocker_detail||selected.packet.blocker||''}\n${(selected.packet.notes||[]).join('\n')}\n${Object.values(selected.packet.files||{}).map(f=>'Attach manually: '+f.suggested_filename).join('\n')}`:'No packet selected.';for(const name of ['open','restore','submitted'])$(name).disabled=!selected}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function currentTab(){const [t]=await chrome.tabs.query({active:true,currentWindow:true});if(!t?.id||!/^https?:/.test(t.url||''))throw Error('Open the application page, then open this extension from Chrome’s toolbar.');return t}
async function permission(t){const frames=await chrome.webNavigation.getAllFrames({tabId:t.id})||[];const main=new URL(t.url),origins=new Set([main.origin+'/*']);const denied=new Set();for(let pass=0;pass<frames.length+1;pass++)for(const f of frames)if(/captcha|turnstile|challenges\.cloudflare/i.test(f.url)||denied.has(f.parentFrameId))denied.add(f.frameId);for(const f of frames){if(denied.has(f.frameId))continue;try{const u=new URL(f.url);if(u.protocol==='https:'&&/(^|\.)(greenhouse\.io|lever\.co|ashbyhq\.com|myworkdayjobs\.com|smartrecruiters\.com|rippling\.com|pinpointhq\.com|successfactors\.com|icims\.com|taleo\.net)$/.test(u.hostname))origins.add(u.origin+'/*')}catch{}}
 const wanted=[...origins];if(!await chrome.permissions.contains({origins:wanted})&&!await chrome.permissions.request({origins:wanted}))throw Error('Site access was not granted. No fields were changed.')}
function report(r){lastReport=r;$('result-section').hidden=false;$('counts').textContent=`Filled ${r.filled} · Skipped ${r.skipped} · Missing ${r.missing}`;$('result').textContent=JSON.stringify(r,null,2);$('warnings').replaceChildren(...[...r.warnings,...r.missing_required.map(x=>'Required-looking field still empty: '+x)].map(t=>{const li=document.createElement('li');li.textContent=t;return li}));const files=Object.values(selected?.packet.files||{});$('attachments').textContent=r.file_inputs.some(f=>!f.has_file)?'Attach resume or requested documents manually'+(files.length?': '+files.map(f=>f.suggested_filename).join(', '):'.'):''}
const action=(id,fn)=>$(id).addEventListener('click',async()=>{const button=$(id);button.disabled=true;try{await fn()}catch(e){status(e.message,true)}finally{button.disabled=false}});
$('file').addEventListener('change',async()=>{try{const file=$('file').files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Packet exceeds 2 MiB.');const p=parsePacket(await file.text());await message('import',{packet:p});$('json').value='';await refresh();status('Packet imported. Review the job and page before restoring.')}catch(e){status(e.message,true)}});
action('import',async()=>{const packet=parsePacket($('json').value);await message('import',{packet});$('json').value='';await refresh();status('Packet imported. Nothing was filled automatically.')});
$('history').addEventListener('change',async()=>{await message('select',{id:$('history').value});await refresh()});
action('open',()=>message('open'));
action('restore',async()=>{const t=await currentTab();if(!selected||new URL(t.url).origin!==new URL(selected.packet.application_url).origin)throw Error('Active page is on a different origin. Review the application URL before restoring.');const current=new URL(t.url),expected=new URL(selected.packet.application_url);if(current.pathname+current.search!==expected.pathname+expected.search&&!$('confirm-page').checked)throw Error('Application path differs. Confirm this is the correct application page.');await permission(t);report(await message('restore',{tabId:t.id,confirmPage:$('confirm-page').checked}));status('Restore finished. Review the values, attach files, solve the captcha yourself, then submit.')});
action('export',async()=>{const t=await currentTab();await permission(t);const r=await message('capture',{tabId:t.id});download(r.packet.id+'.json',r.packet);status('Exported visible supported controls. '+r.capture.warnings.join(' '))});
action('submitted',async()=>{if(!$('confirm-submit').checked)throw Error('Confirm that you personally submitted on the employer’s website.');const result=await message('submitted',{confirm:true});download(result.id+'-result.json',result);await refresh();status('Marked submitted locally. No tracker API was contacted.')});
action('clear',async()=>{if(!confirm('Clear the last five locally stored packets? Downloaded files are unchanged.'))return;await message('clear');selected=null;await refresh();status('Local packet history cleared.')});
action('copy',async()=>{if(!lastReport)throw Error('Run Restore first.');await navigator.clipboard.writeText(JSON.stringify(lastReport,null,2));status('Copied the restore report without field values.')});
void refresh().catch(e=>status(e.message,true));
