const insensitive=s=>s.replace(/\\.|[a-z]/g,c=>c.startsWith('\\')?c:`[${c}${c.toUpperCase()}]`);
const secret=insensitive('password|passcode|\\botp\\b|one[-_ ]?time[-_ ]?code|verification[-_ ]?code|csrf|xsrf|captcha|turnstile|session[-_ ]?(?:cookie|token)|(?:access|refresh|auth|id)[-_ ]?token|(?:credit[-_ ]?card|card[-_ ]?number)|\\bcvv\\b|\\bcvc\\b');
const safeText={type:'string',maxLength:2000,pattern:`^(?![\\s\\S]*(?:${secret}))[\\s\\S]*$`};
const text={type:'string',maxLength:2000};
const url={type:'string',format:'uri',maxLength:8000,pattern:'^https?://[^/@\\s]+(?::[0-9]+)?(?:[/?#]|$)',not:{pattern:'[?&](?:access_token|id_token|refresh_token|password|otp|code|session|sessionid|csrf)='}};
const profileKeys=['first','last','full_name','email','phone','phone_formatted','address','address_line1','address_line2','city','state','zip','country','website','linkedin','github','school','degree','major','graduation_year','salary'];
export const packetSchema={
 $schema:'http://json-schema.org/draft-07/schema#',$id:'https://github.com/kvn8888/kvn8888.github.io/releases/download/ats-handoff-v1.0.2/handoff-packet.schema.json',title:'ATS human handoff packet',type:'object',additionalProperties:false,
 required:['schema_version','id','created_at','application_url','status'],
 properties:{schema_version:{const:'1.0'},id:{type:'string',pattern:'^(?:[0-9]{8}-[0-9]{6}-[a-zA-Z0-9-]{1,80}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$'},created_at:{type:'string',format:'date-time'},application_url:url,status:{enum:['captcha_blocked','ready_for_human','imported','submitted','abandoned','expired']},company:text,role:text,ats:{type:'string',minLength:1,maxLength:100,description:'greenhouse, lever, ashby, workday, smartrecruiters, rippling, pinpoint, successfactors, icims, taleo, google_forms, unknown; additional provider names allowed'},blocker:text,blocker_detail:{type:'string',maxLength:10000},fields:{type:'array',maxItems:500,items:{$ref:'#/definitions/field'}},profile_overlay:{type:'object',additionalProperties:false,properties:{...Object.fromEntries(profileKeys.map(k=>[k,text])),autofill_lies_to_overwrite:{type:'array',maxItems:100,items:text}}},files:{type:'object',maxProperties:20,additionalProperties:{type:'object',additionalProperties:false,properties:{label:text,suggested_filename:text,box_path:text,sha256:{type:'string',pattern:'^[a-fA-F0-9]{64}$'}},required:['suggested_filename']}},notes:{type:'array',maxItems:100,items:{type:'string',maxLength:10000}},agent:{type:'object',additionalProperties:false,properties:{source:text,box_capture:{type:'boolean'}}},evidence:{type:'object',additionalProperties:false,properties:{screenshot_box_path:{anyOf:[text,{type:'null'}]}}}},
 definitions:{field:{type:'object',additionalProperties:false,required:['value'],anyOf:[{required:['selectors'],properties:{selectors:{minItems:1}}},{required:['name'],properties:{name:{minLength:1}}},{required:['label'],properties:{label:{minLength:1}}},{required:['placeholder'],properties:{placeholder:{minLength:1}}}],properties:{name:safeText,label:safeText,placeholder:safeText,selectors:{type:'array',maxItems:10,items:{...safeText,minLength:1}},value:{anyOf:[{type:'string',maxLength:50000},{type:'number'},{type:'boolean'},{type:'null'},{type:'array',maxItems:100,items:{type:'string',maxLength:2000}}]},type:{enum:['text','email','tel','textarea','select','checkbox','radio','date','file','hidden','other']},option_value:text,frame_hint:text,frame_url:url,confidence:{type:'number',minimum:0,maximum:1},required:{type:'boolean'}},allOf:[{if:{required:['type'],properties:{type:{enum:['hidden','file']}}},then:{properties:{value:{type:'null'}}}}]}}
};
