import {readFile,writeFile,mkdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {fileURLToPath} from 'node:url'
import path from 'node:path'
import openapiTS,{astToString} from 'openapi-typescript'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..')
const packetSchema=JSON.parse(await readFile(path.join(root,'jobs/handoff/handoff-packet.schema.json'),'utf8'))
const packetSource='// Generated from jobs/handoff/handoff-packet.schema.json.\nexport const handoffPacketSchema = '+JSON.stringify(packetSchema,null,2)+' as const\n'
const packetTarget=path.join(root,'homepage/src/lib/handoffPacketSchema.ts');
if(process.argv.includes('--check')){if(await readFile(packetTarget,'utf8')!==packetSource)throw Error('Generated handoff schema drift')}else await writeFile(packetTarget,packetSource)
const {buildOpenApi,API_VERSION,CLIENT_VERSION,BASE_URL,jobWorkflowContract}=await import('../../homepage/src/lib/jobApiDefinition');
const spec=buildOpenApi();const json=JSON.stringify(spec,null,2)+'\n'
const guide=await readFile(path.join(root,'jobs/guide.md'),'utf8')
const contractHash=createHash('sha256').update(json).digest('hex')
const revision=createHash('sha256').update(json+guide+JSON.stringify(jobWorkflowContract)).digest('hex')
const cliSource=await readFile(path.join(root,'jobs/cli/jobs-workflow.mjs'),'utf8')
const output={'homepage/src/lib/handoffPacketSchema.ts':'// Generated from jobs/handoff/handoff-packet.schema.json.\nexport const handoffPacketSchema = '+JSON.stringify(packetSchema,null,2)+' as const\n','jobs/cli/jobs-workflow.mjs':cliSource.replace(/export const VERSION='[^']+';/,`export const VERSION='${CLIENT_VERSION}';`),'jobs/generated/release-config.json':JSON.stringify({version:CLIENT_VERSION,api_version:API_VERSION},null,2)+'\n','jobs/extension/src/shared/version.ts':`// Generated.\nexport const CLIENT_VERSION='${CLIENT_VERSION}'\n`,'jobs/generated/openapi.json':json,'jobs/extension/src/shared/api-types.ts':astToString(await openapiTS(spec as any)), 'homepage/src/lib/jobWorkflowPublished.ts':`// Generated by jobs/scripts/generate.ts. Do not edit.\nexport const published = ${JSON.stringify({api_version:API_VERSION,client_version:CLIENT_VERSION,base_url:BASE_URL,contract_hash:contractHash,revision,openapi:spec,guide},null,2)} as const\n`}
for(const [file,content] of Object.entries(output)){const target=path.join(root,file);if(process.argv.includes('--check')){if(await readFile(target,'utf8')!==content)throw Error(`Generated artifact drift: ${file}`)}else{await mkdir(path.dirname(target),{recursive:true});await writeFile(target,content)}}
console.log(JSON.stringify({contract_hash:contractHash,revision,files:Object.keys(output)}))
