// Uses the actual personal-site handlers against disposable SQLite; no production config is loaded.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module'),{createServer}=require('node:http')
module.exports=async function fixture(db,key,readerKey){
 const root=process.env.TRACKER_HOMEPAGE||path.resolve(__dirname,'../../../homepage')
 const requireSite=createRequire(path.join(root,'package.json')),ts=requireSite('typescript'),cache=new Map()
 const mocks={'@/auth':{auth:async()=>null},'@/lib/secrets':{getSecret:async name=>({JOBS_API_KEY:key,JOBS_READ_API_KEY:readerKey})[name]}}
 function load(relative){const filename=path.join(root,relative);if(cache.has(filename))return cache.get(filename);const module={exports:{}};const source=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;function resolver(name){if(mocks[name])return mocks[name];if(name.startsWith('@/'))return load('src/'+name.slice(2)+'.ts');if(name.startsWith('.')){const rel=path.relative(root,path.resolve(path.dirname(filename),name+'.ts'));const alias='@/'+rel.replace(/^src\//,'').replace(/\.ts$/,'');return mocks[alias]||load(rel)}return requireSite(name)}vm.runInThisContext(`(function(require,module,exports){${source}\n})`,{filename})(resolver,module,module.exports);cache.set(filename,module.exports);return module.exports}
 const schema=load('src/lib/jobsDb.ts');await schema.ensureJobsSchema(db);mocks['@/lib/jobsDb']={...schema,getJobsDb:async()=>db}
 await load('src/lib/jobCollectionSchema.ts').ensureCollectionSchema(db)
 await load('src/lib/jobWorkflowSchema.ts').ensureWorkflowSchema(db)
 return ()=>createServer(async(req,res)=>{try{const parts=req.url.split('?')[0].split('/').filter(Boolean);let route,params={};if(parts[1]==='job-workflow'){route='src/app/api/job-workflow/[...path]/route.ts';params={path:parts.slice(2)}}else if(parts[1]==='job-collection'){route=parts[2]?'src/app/api/job-collection/[id]/route.ts':'src/app/api/job-collection/route.ts';params={id:parts[2]}}else if(parts[1]==='jobs'){route=parts[2]?'src/app/api/jobs/[id]/route.ts':'src/app/api/jobs/route.ts';params={id:parts[2]}}else{res.writeHead(404);res.end('{}');return}
 const chunks=[];for await(const c of req)chunks.push(c);const request=new Request('http://127.0.0.1:43128'+req.url,{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})});const response=await load(route)[req.method](request,{params:Promise.resolve(params)});if(response.status>=200&&response.status<300){const defs=load('src/lib/jobApiDefinition.ts');const actualPath=req.url.split('?')[0];const op=defs.endpoints.find(op=>op.method.toUpperCase()===req.method&&new RegExp('^'+op.path.replace('{id}','[^/]+')+'$').test(actualPath));if(op&&op.response!=='guide'){const parsed=defs.responseSchemas[op.response].safeParse(await response.clone().json());if(!parsed.success)throw Error('Response schema mismatch '+op.operationId+': '+parsed.error.message)}}res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text())}catch(e){console.error('Fixture error',e.message);res.writeHead(500);res.end(JSON.stringify({error:e.message}))}})
}
