import {writeFileSync} from 'node:fs';
const param=(name,where,schema,required=false)=>({name,in:where,required,schema});
const document={type:'object',required:['path','revision','parent','actor','updated_at','reason','content','sha256'],properties:{path:{type:'string'},revision:{type:'string'},parent:{type:['string','null']},actor:{type:'string'},updated_at:{type:'string',format:'date-time'},reason:{type:'string'},content:{type:'string'},sha256:{type:'string'}}};
const response=(description,schema)=>({description,content:{'application/json':{schema}}});
const errors=Object.fromEntries([400,401,403,404,405,412,413,428,503].map(n=>[n,response({412:'Concurrent modification: reread and merge',428:'Write precondition required'}[n]||'Request error',{type:'object',required:['error'],properties:{error:{type:'string'}}})]));
const s={openapi:'3.1.0',info:{title:'Private job-search workspace',version:'1.0.0',description:'Markdown workspace; all document data requires a bearer credential. Conditional writes and immutable revision history. Job application data stays in the existing tracker API.'},servers:[{url:'https://job-search-workspace.kvn-c8888.workers.dev'}],security:[{bearer:[]}],components:{securitySchemes:{bearer:{type:'http',scheme:'bearer'}},schemas:{Document:document}},paths:{}};
for(const path of ['/discovery','/openapi.json'])s.paths[path]={get:{operationId:path==='/discovery'?'discoverWorkspace':'workspaceOpenapi',security:[],responses:{200:response('Public metadata',{type:'object'})}}};
s.paths['/v1/connection']={get:{operationId:'workspaceConnection',responses:{200:response('Authenticated identity',{type:'object',properties:{actor:{type:'string'},role:{type:'string'}}}),...errors}}};
s.paths['/v1/documents']={get:{operationId:'listDocuments',parameters:[param('prefix','query',{type:'string'}),param('cursor','query',{type:'string'})],responses:{200:response('Paginated document paths',{type:'object',properties:{documents:{type:'array',items:{type:'object',properties:{path:{type:'string'}}}},cursor:{type:['string','null']}}}),...errors}}};
s.paths['/v1/documents/{path}']={parameters:[param('path','path',{type:'string',description:'Slash-separated canonical Markdown path, such as automation/agents/muse.md'},true)],get:{operationId:'readDocument',parameters:[param('history','query',{type:'string',enum:['1']}),param('revision','query',{type:'string'})],responses:{200:{...response('Current/historical document or newest 100 committed history entries',{oneOf:[document,{type:'object',properties:{revisions:{type:'array',items:{type:'object'}},truncated:{type:'boolean'},etag:{type:'string'}}}]}),headers:{ETag:{schema:{type:'string'},description:'Current head ETag, required for updates'}}},...errors}},put:{operationId:'writeDocument',description:'No unconditional writes. Readback after ambiguous timeouts before retrying. To restore, read a historical revision and save its content against the current ETag. Agents cannot edit another agent process file or archives. A source/reason is mandatory.',parameters:[param('If-Match','header',{type:'string'}),param('If-None-Match','header',{type:'string',enum:['*']})],requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['content','reason'],properties:{content:{type:'string'},reason:{type:'string',minLength:3,maxLength:2000}}},example:{content:'# Synthetic note\nTest content',reason:'Synthetic example; no personal data'}}}},responses:{200:response('Saved revision',document),201:response('Created document',document),...errors}}};
writeFileSync(new URL('./openapi.json',import.meta.url),JSON.stringify(s,null,2)+'\n');

writeFileSync(new URL('./openapi.mjs',import.meta.url),'export default '+JSON.stringify(s)+';\n');
